$(document).ready(function(){
		$("#profile").hover(function(){
			$("#prof-info").slideToggle("slow");
		});
		$("#crypto").hover(function(){
			$("#cryp-info").slideToggle("slow");
		});
		$("#droid").hover(function(){
			$("#droid-info").slideToggle("slow");
		});
		$("#app").hover(function(){
			$("#app-info").slideToggle("slow");
		});
		$("#finance").hover(function(){
			$("#finance-info").slideToggle("slow");
		});
		$("#carhire").hover(function(){
			$("#carhire-info").slideToggle("slow");
		});
});